apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kafka-watchdog.fullname" . }}
  labels:
    app: {{ template "kafka-watchdog.name" . }}
    chart: {{ template "kafka-watchdog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "kafka-watchdog.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    {{- end }}
      labels:
    {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
    {{- end }}
        app: {{ template "kafka-watchdog.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            {{- range $key, $value := .Values.env_vars }}
              - name: {{ $key }}
                value: {{ $value  | quote }}
            {{- end }}
          ports: []
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
